# Generated by Django 5.0.4 on 2024-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('stock_code', models.CharField(max_length=10, verbose_name='證券代號')),
                ('stock_name', models.TextField(verbose_name='證券名稱')),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='開盤價')),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高價')),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低價')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='收盤價')),
                ('pos_neg', models.CharField(max_length=1, verbose_name='漲跌(+/-)')),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='漲跌價差')),
                ('total_volume', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='成交股數')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交金額')),
            ],
        ),
    ]
