# Generated by Django 5.0.4 on 2024-04-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='證券代號'),
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock_data',
        ),
    ]
