# Generated by Django 5.0.4 on 2024-05-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_userprofile_alter_stock_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
