# Generated by Django 5.0.4 on 2024-05-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('stock_code', models.CharField(max_length=10, verbose_name='證券代號')),
                ('stock_name', models.TextField(verbose_name='證券名稱')),
                ('Distribution_Date', models.CharField(max_length=50, verbose_name='發放期間')),
                ('Belong', models.CharField(max_length=255, verbose_name='所屬期間')),
                ('Cash_Dividend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='現金股利')),
                ('stock_Dividend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='股票股利')),
                ('Cash_Yield', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='現金殖利率')),
                ('Ex_Date_Close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='除息日昨收價')),
                ('Ex_Dividend_Date', models.CharField(max_length=50, verbose_name='除息日')),
                ('Ex_Right_Date', models.CharField(max_length=50, verbose_name='除權日')),
                ('Cash_Dividend_Date', models.CharField(max_length=50, verbose_name='現金股利發放日')),
                ('stock_Dividend_Date', models.CharField(max_length=50, verbose_name='股票股利發放日')),
                ('Back_To_Close_Date', models.IntegerField(max_length=10, verbose_name='填息天數')),
            ],
            options={
                'db_table': 'dividend',
            },
        ),
        migrations.CreateModel(
            name='industry_hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='證券代號')),
                ('stock_name', models.TextField(verbose_name='證券名稱')),
                ('industry_hold', models.CharField(max_length=50, verbose_name='持股產業')),
                ('percentage', models.CharField(max_length=10, verbose_name='百分比')),
            ],
            options={
                'db_table': 'industry_hold',
            },
        ),
        migrations.CreateModel(
            name='stock_hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=10, verbose_name='證券代號')),
                ('stock_name', models.TextField(verbose_name='證券名稱')),
                ('stock_hold', models.CharField(max_length=50, verbose_name='持股證券')),
                ('percentage', models.CharField(max_length=10, verbose_name='百分比')),
            ],
            options={
                'db_table': 'stock_hold',
            },
        ),
    ]
