# Generated by Django 5.0.4 on 2024-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_dividend_industry_hold_stock_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry_hold',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock_hold',
            name='id',
        ),
        migrations.AlterField(
            model_name='dividend',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='證券代號'),
        ),
        migrations.AlterField(
            model_name='industry_hold',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='證券代號'),
        ),
        migrations.AlterField(
            model_name='stock_hold',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='證券代號'),
        ),
    ]
