# Generated by Django 5.0.4 on 2024-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_industry_hold_id_remove_stock_hold_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuridicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_code', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=50)),
                ('foreign_investors_buy', models.IntegerField()),
                ('foreign_investors_sell', models.IntegerField()),
                ('foreign_investors_diff', models.IntegerField()),
                ('foreign_self_buy', models.IntegerField()),
                ('foreign_self_sell', models.IntegerField()),
                ('foreign_self_diff', models.IntegerField()),
                ('investment_trust_buy', models.IntegerField()),
                ('investment_trust_sell', models.IntegerField()),
                ('investment_trust_diff', models.IntegerField()),
                ('dealer_total_diff', models.IntegerField()),
                ('dealer_self_buy', models.IntegerField()),
                ('dealer_self_sell', models.IntegerField()),
                ('dealer_self_diff', models.IntegerField()),
                ('dealer_hedge_buy', models.IntegerField()),
                ('dealer_hedge_sell', models.IntegerField()),
                ('dealer_hedge_diff', models.IntegerField()),
                ('total_diff', models.IntegerField()),
            ],
            options={
                'db_table': 'juridical_data',
            },
        ),
        migrations.RenameModel(
            old_name='industry_hold',
            new_name='IndustryHold',
        ),
        migrations.RenameModel(
            old_name='stock_hold',
            new_name='StockHold',
        ),
        migrations.RenameField(
            model_name='dividend',
            old_name='stock_Dividend_Date',
            new_name='stock_Dividends_Date',
        ),
        migrations.RenameField(
            model_name='industryhold',
            old_name='industry_hold',
            new_name='industry_holder',
        ),
        migrations.RenameField(
            model_name='stockhold',
            old_name='stock_hold',
            new_name='stock_holder',
        ),
    ]
