# Generated by Django 5.0.4 on 2024-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_juridicaldata_rename_industry_hold_industryhold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juridicaldata',
            name='id',
        ),
        migrations.AlterField(
            model_name='juridicaldata',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
